spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: bafafa
bafafa:
  auth:
    jwt-secret: ${JWT_SECRET:dev-only-secret-troque-em-producao-0123456789}
    access-token-ttl: 15m
    refresh-token-ttl: 30d
    refresh-cookie-secure: false